### PR TITLE
cmake: cleaned up and implemented the rest of the features

### PR DESCRIPTION
**Pull request by gauteh**
Hi,

For reference. It is not necessary to merge this into your cmake branch.

I cleaned up your PR and implemented the remaining issues:
* #23 
* #7 
* #6 

I also fixed:
* gir file was installed in wrong dir (check if correct on Mac now)
* gir always used gmime 3 as dep (now using correct gmime)

If everything looks good, cmake support is ready to be merged into astroid.

### CODE REVIEW

**Comment by c-alpha** [comment]
**Cool, thanks for your contributions, @gauteh !** I have merged it anyway, and made some small fixes, and small enhancements along the way, too.

The `markdown` and `crypto` tests are failing for me, btw.

**Comment by gauteh** [comment]
Thanks!

You probably need to install `marked` for markdown to work. `crypto` requires a working gpg setup.. not sure if it works on mac.

**Comment by c-alpha** [comment]
On 2017-11-15, at 12:31 , Gaute Hope <notifications@github.com> wrote:

> [...]
> You probably need to install marked for markdown to work.

Ah, that explains.

> crypto requires a working gpg setup.. not sure if it works on mac.
> [...]

I have gpg 2.2.1 installed via homebrew, and it works fine so far. I'll have a closer look at why it fails.

**Comment by c-alpha** [comment]
Just re-ran the tests and it looks like the crypto one fails with a `SIGSEGV`. See log excerpt below.

Near the bottom it says `crypto: failed to create gpg context.`, but then goes on trying to encrypt something. For some reason the `GMimeCryptoContext *` in `bool Crypto::create_gpg_context ()` is not created correctly. Either something in gpg 2.2.1 breaks GMime, or the `GMIME_MAJOR_VERSION` test somehow fails?

The comment near the top of `GMimeObject * Crypto::decrypt_and_verify (GMimeObject * part)` could also hint to the key handling having changed with gpg 2.2.1. This has indeed changed (see e.g. http://www.condition-alpha.com/blog/?p=1467). Maybe your test keys are no longer found or trusted by the new version?

```
16/17 Testing: crypto
16/17 Test: crypto
Command: "/Users/alexanderadolf/Projects/astroid/_build/tests/run_test.sh" "/Users/alexanderadolf/Projects/astroid" "/Users/alexanderadolf/Projects/astroid/_build" "test_crypto"
Directory: /Users/alexanderadolf/Projects/astroid/_build/tests
"crypto" start time: Nov 15 17:58 CET
Output:
----------------------------------------------------------
Source dir: /Users/alexanderadolf/Projects/astroid
Build dir:  /Users/alexanderadolf/Projects/astroid/_build
Running: test_crypto..
~/Projects/astroid/_build ~/Projects/astroid/_build/tests
[17:58:22.218153] [0x00007fff8ef82340] [info] welcome to astroid! - v0.10.2-26-gf7787997
[17:58:22.218341] [0x00007fff8ef82340] [debug] utf8: true, UTF-8
[17:58:22.219943] [0x00007fff8ef82340] [info] cf: loading test config.
[17:58:22.220713] [0x00007fff8ef82340] [debug] cf: using home and config_dir directory: /Users/alexanderadolf/Projects/astroid/_build/tests/test_home
[17:58:22.220796] [0x00007fff8ef82340] [info] cf: test config, loading defaults.
[17:58:22.225025] [0x00007fff8ef82340] [info] date: init.
[17:58:22.225811] [0x00007fff8ef82340] [info] db path: /Users/alexanderadolf/Projects/astroid/_build/tests/mail/test_mail
[17:58:22.227901] [0x00007fff8ef82340] [debug] searches: loading history..
[17:58:22.227954] [0x00007fff8ef82340] [info] ac: initializing accounts..
[17:58:22.228073] [0x00007fff8ef82340] [info] ac: setup account: charlie for Charlie Root (default: true)
[17:58:22.228117] [0x00007fff8ef82340] [info] plugins: starting manager..
[17:58:22.228247] [0x00007fff8ef82340] [error] plugins: GI_TYPELIB_PATH already set, not touching..
[17:58:22.228274] [0x00007fff8ef82340] [debug] plugin: adding path: /Users/alexanderadolf/Projects/astroid/_build/tests/test_home/plugins
[17:58:22.228828] [0x00007fff8ef82340] [debug] plugins: refreshing..
[17:58:22.229078] [0x00007fff8ef82340] [debug] plugins: found 2 plugins.
[17:58:22.229109] [0x00007fff8ef82340] [debug] plugins: loading: basic plugin
[17:58:22.327833] [0x00007fff8ef82340] [debug] plugins: loaded: basic plugin
[17:58:22.327992] [0x00007fff8ef82340] [debug] plugins: registering astroid plugin..
[17:58:22.328146] [0x00007fff8ef82340] [debug] plugins: loading: threadindexplugin
[17:58:22.363273] [0x00007fff8ef82340] [debug] plugins: loaded: threadindexplugin
[17:58:22.363454] [0x00007fff8ef82340] [debug] plugins: registering threadindex plugin..
[17:58:22.363915] [0x00007fff8ef82340] [debug] plugins: activating astroid plugin: basic plugin
[17:58:22.364012] [0x00007fff8ef82340] [info] global actions: set up.
[17:58:22.364174] [0x00007fff8ef82340] [info] poll: setting up.
[17:58:22.364224] [0x00007fff8ef82340] [debug] poll: interval: 0
[17:58:22.364279] [0x00007fff8ef82340] [info] poll: periodic polling disabled.
[17:58:22.364306] [0x00007fff8ef82340] [trace] cy: account gpg: gaute@astroidmail.bar
[17:58:22.364338] [0x00007fff8ef82340] [debug] cm: initialize..
[17:58:22.364478] [0x00007fff8ef82340] [debug] cm: deinitialized.
[17:58:22.364630] [0x00007fff8ef82340] [debug] actions: cleaning up remaining actions..
[17:58:22.365240] [0x00007fff8ef82340] [info] welcome to astroid! - v0.10.2-26-gf7787997
[17:58:22.365283] [0x00007fff8ef82340] [debug] utf8: true, UTF-8
[17:58:22.365315] [0x00007fff8ef82340] [info] cf: loading test config.
[17:58:22.365411] [0x00007fff8ef82340] [debug] cf: using home and config_dir directory: /Users/alexanderadolf/Projects/astroid/_build/tests/test_home
[17:58:22.365444] [0x00007fff8ef82340] [info] cf: test config, loading defaults.
[17:58:22.366831] [0x00007fff8ef82340] [info] date: init.
[17:58:22.366927] [0x00007fff8ef82340] [info] db path: /Users/alexanderadolf/Projects/astroid/_build/tests/mail/test_mail
[17:58:22.367043] [0x00007fff8ef82340] [debug] searches: loading history..
[17:58:22.367074] [0x00007fff8ef82340] [info] ac: initializing accounts..
[17:58:22.367161] [0x00007fff8ef82340] [info] ac: setup account: charlie for Charlie Root (default: true)
[17:58:22.367202] [0x00007fff8ef82340] [info] plugins: starting manager..
[17:58:22.367215] [0x00007fff8ef82340] [error] plugins: GI_TYPELIB_PATH already set, not touching..
[17:58:22.367227] [0x00007fff8ef82340] [debug] plugin: adding path: /Users/alexanderadolf/Projects/astroid/_build/tests/test_home/plugins
[17:58:22.367476] [0x00007fff8ef82340] [debug] plugins: refreshing..
[17:58:22.367864] [0x00007fff8ef82340] [debug] plugins: found 2 plugins.
[17:58:22.367897] [0x00007fff8ef82340] [debug] plugins: loading: basic plugin
[17:58:22.367908] [0x00007fff8ef82340] [debug] plugins: loaded: basic plugin
[17:58:22.367937] [0x00007fff8ef82340] [debug] plugins: registering astroid plugin..
[17:58:22.367981] [0x00007fff8ef82340] [debug] plugins: loading: threadindexplugin
[17:58:22.367995] [0x00007fff8ef82340] [debug] plugins: loaded: threadindexplugin
[17:58:22.368012] [0x00007fff8ef82340] [debug] plugins: registering threadindex plugin..
[17:58:22.368141] [0x00007fff8ef82340] [debug] plugins: activating astroid plugin: basic plugin
[17:58:22.368184] [0x00007fff8ef82340] [info] global actions: set up.
[17:58:22.368227] [0x00007fff8ef82340] [info] poll: setting up.
[17:58:22.368252] [0x00007fff8ef82340] [debug] poll: interval: 0
[17:58:22.368281] [0x00007fff8ef82340] [info] poll: periodic polling disabled.
[17:58:22.368308] [0x00007fff8ef82340] [trace] cy: account gpg: gaute@astroidmail.bar
[17:58:22.368325] [0x00007fff8ef82340] [debug] cm: initialize..
[17:58:22.368429] [0x00007fff8ef82340] [trace] cm: writing utf-8 text to message body: This is test: æøå.
 > testing
testing
...
[17:58:22.368464] [0x00007fff8ef82340] [trace] build:
[17:58:22.368475] [0x00007fff8ef82340] [debug] cm: build..
[17:58:22.368607] [0x00007fff8ef82340] [trace] finalize:
[17:58:22.368645] [0x00007fff8ef82340] [debug] cm: finalize..
[17:58:22.368878] [0x00007fff8ef82340] [debug] crypto: gpg: gpg2
[17:58:22.368919] [0x00007fff8ef82340] [debug] crypto: in test
[17:58:22.368951] [0x00007fff8ef82340] [error] crypto: failed to create gpg context.
[17:58:22.369561] [0x00007fff8ef82340] [debug] cr: encrypting for:
[17:58:22.369606] [0x00007fff8ef82340] [debug] astrid@astroidmail.bar
[17:58:22.369632] [0x00007fff8ef82340] [debug] gaute@astroidmail.bar

(<unknown>:78401): gmime-CRITICAL **: g_mime_multipart_encrypted_encrypt: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed
Running 7 test cases...
unknown location:0: fatal error: in "GPGEncryption/crypto_compose_test_encrypt_body": memory access violation at address: 0x00000008: no mapping at fault address
/Users/alexanderadolf/Projects/astroid/tests/test_crypto.cc:33: last checkpoint: "crypto_compose_test_encrypt_body" test entry

*** 1 failure is detected in the test module "TestCrypto"
/Users/alexanderadolf/Projects/astroid/_build/tests/run_test.sh: line 57: 78401 Segmentation fault: 11  ./tests/${TEST}
<end of output>
Test time =   0.32 sec
----------------------------------------------------------
Test Failed.
"crypto" end time: Nov 15 17:58 CET
"crypto" time elapsed: 00:00:00
----------------------------------------------------------
```

**Comment by gauteh** [comment]
Does regular crypto work in astroid?

**Comment by c-alpha** [comment]
> On 2017-11-15, at 12:31 , Gaute Hope ***@***.***> wrote:
> >  [...]
> >  You probably need to install marked for markdown to work.
>
> Ah, that explains.

Just wondering: this seems like we should have a new configuration flag, e.g. DISABLE_MARKDOWN or similar? Marked does not seem to be on homebrew; does it provide information via `pkg-config`?

**Comment by gauteh** [comment]
It’s a runtime dependency, you can install it via npm I think on mac.

ons. 15. nov. 2017 kl. 21:38 skrev c-alpha <notifications@github.com>:

**Comment by c-alpha** [comment]
On 2017-11-15, at 21:45 , Gaute Hope <notifications@github.com> wrote:

> It’s a runtime dependency, you can install it via npm I think on mac.
> [...]

No npm here...

If the availability of marked could be detected from the cmake file (e.g. if it  provides pkg-config infromation), we could skip the markdown test it it's not installed.

**Comment by gauteh** [comment]
c-alpha writes on november 15, 2017 21:56:
> On 2017-11-15, at 21:45 , Gaute Hope <notifications@github.com> wrote:
> 
>> It’s a runtime dependency, you can install it via npm I think on mac.
>> [...]
> 
> No npm here...
> 
> If the availability of marked could be detected from the cmake file (e.g. if it  provides pkg-config infromation), we could skip the markdown test it it's not installed.
> 

Fair enough. If the `marked` command is not available skip the test. 
Hopefully cmake has a mechanism for making the test should_fail or 
skipped.

**Pull request merged**
